services: 
  anki-desktop: 
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ~/.local/share/Anki2:/config/app/Anki2
      - ~/backups:/config/app/backups
    ports:
      - 3000:3000
      # Anki Connect port
      - 8765:8765
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: