services: 
  anki-desktop: 
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ~/.local/share/Anki2:/config/app/Anki2
      - ~/backups:/config/app/backups
    ports:
      - 3000:3000
      # Anki Connect port
      - 8765:8765

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_vocab_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mainapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - .env.container
    depends_on:
      - postgres-db

volumes:
  postgres-data: